version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TestLicitaNetCoder
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - "3306:3306"
   

